# =========================
# Site: Alicia García-Sierra
# Powered by Jekyll · Theme: al-folio · Photos from Unsplash
# =========================

# --- Basic site settings ---
title: "Alicia García-Sierra"
description: "Postdoctoral researcher"
url: "https://aliciagarciasierra.github.io"
baseurl: ""                 # keep empty for username.github.io root
locale: "en-US"
timezone: "Europe/London"
repository: "aliciagarciasierra/aliciagarciasierra.github.io"

# --- Theme ---
remote_theme: alshedivat/al-folio

# --- Plugins (GitHub Pages–supported) ---
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag

# --- Author / profile ---
author:
  name: "Alicia García-Sierra"
  avatar: "assets/img/profileali.jpeg"   # place your image here
  bio: "Postdoctoral researcher"
  location: "Lausanne"
  employer: "LIVES Centre, University of Lausanne"
  email: "alicia.garciasierra@unil.ch"
  scholar: "https://scholar.google.com/citations?user=a-VWISkAAAAJ&hl=es"
  orcid: "https://orcid.org/0000-0002-2025-4003"
  github: "https://github.com/aliciagarciasierra"
  linkedin: "https://www.linkedin.com/in/aliciagsierra/"

# --- Navigation ---
navbar:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "News"
    url: /news/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# --- Footer ---
footer_text: "Powered by Jekyll · Theme: al-folio · Photos from Unsplash"

# --- Posts / pagination ---
paginate: 5
paginate_path: /page:num/
permalink: /:categories/:title/
feed:
  path: feed.xml

# --- Markdown / code ---
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# --- Collections ---
# al-folio ships with 'projects' and 'news'. Keep teaching/publications too.
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

# --- Defaults (layouts) ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: news
    values:
      layout: post
  - scope:
      path: ""
      type: teaching
    values:
      layout: page
  - scope:
      path: ""
      type: publications
    values:
      layout: page
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# --- Includes / excludes (keep minimal) ---
include:
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - README
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - tmp
  - log

# --- Misc ---
future: false
