# --- Basic site settings ---
title: "Alicia García-Sierra"
description: "Postdoctoral researcher"
url: "https://aliciagarciasierra.github.io"
baseurl: ""  # leave empty for username.github.io root
locale: "en-US"
timezone: "Europe/London"

# If this repo is your user site, this can be omitted or set to your repo
repository: "aliciagarciasierra/aliciagarciasierra.github.io"

# --- Theme ---
remote_theme: alshedivat/al-folio

# GitHub Pages–supported plugins
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# --- Author / profile (used in sidebar/header blocks) ---
author:
  name: "Alicia García-Sierra"
  avatar: "assets/img/profileali.jpeg"   # move your image to /assets/img/
  bio: "Postdoctoral researcher"
  location: "Lausanne"
  employer: "LIVES Centre, University of Lausanne"
  email: "alicia.garciasierra@unil.ch"
  scholar: "https://scholar.google.com/citations?user=a-VWISkAAAAJ&hl=es"
  orcid: "https://orcid.org/0000-0002-2025-4003"
  github: "https://github.com/aliciagarciasierra"
  linkedin: "https://www.linkedin.com/in/aliciagsierra/"

# --- Navigation (adjust paths as your pages/collections are set up) ---
navbar:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/

# --- Footer ---
footer_text: "Powered by Jekyll"

# --- Posts / pagination (optional) ---
paginate: 5
paginate_path: /page:num/

# --- Markdown / code ---
markdown: kramdown
highlighter: rouge

# --- Feeds / SEO basics ---
feed:
  path: feed.xml
permalink: /:categories/:title/

# --- Collections (start simple; you can expand later) ---
# al-folio ships with 'projects' and 'news' collections by default.
# Keep any you actively use; otherwise migrate content gradually.
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/

# --- Defaults (leaner than academicpages; use generic layouts) ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: page
  - scope:
      path: ""
      type: news
    values:
      layout: post
  - scope:
      path: ""
      type: teaching
    values:
      layout: page
  - scope:
      path: ""
      type: publications
    values:
      layout: page
